- eagerx_core/src/eagerx_core/gui/rxgui.py
- eagerx_core/src/eagerx_core/gui/templates/ui_pyqt6.py
- eagerx_core/src/eagerx_core/gui/templates/ui_pyside6.py
- eagerx_core/src/eagerx_core/utils/pyqtgraph_utils.py
Add support for the latest version of pyqtgraph and fix bug in converter dialog
> Fix converter dialog

- eagerx_core/src/eagerx_core/rxgraph.py
- eagerx_core/src/eagerx_core/rxoperators.py
- eagerx_core/src/eagerx_core/utils/utils.py
With this PR, we can add output converters to sensor outputs.
@jelledouwe  Can you check whether this works with your angle wrapping converter?
> Added output converters in simnodes

- .github/workflows/ci.yml
- Dockerfile
- eagerx/__init__.py
- pyproject.toml
- scripts/build_docker.sh
Fix docker and update to version 0.1.2
> Fix docker

- eagerx/bridges/test/enginestates.py
- eagerx/core/env.py
- eagerx/core/graph.py
- eagerx/core/rx_pipelines.py
- examples/example_test.py
Closes #69 and a bug fix for action space converters.
> Ft first reset

- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
- tests/test_graph.py
- tests/test_graph_engine.py
- tests/test_integration_openai_bridge.py
- tests/test_integration_test_bridge.py
adds timeouts to individual tests and overall github CI
> ci: timeouts added to github ci and tests

- eagerx/core/colab_render.py
- eagerx/core/graph.py
- eagerx/core/nodes.py
- examples/example_openai.py
- poetry.lock
Uses the Colab render node if we are using google colab
> fix: add colab render

- Dockerfile
- Makefile
- scripts/build_docker.sh
Update docker:
- add sudo command
- fix makefile (make command was missing)
- install eagerx-tutorials for docker with stable-baselines 
> chore: update docker

- eagerx/bridges/openai_gym/enginenodes.py
- eagerx/core/register.py
- poetry.lock
- pyproject.toml
> fix: virtual disp

- eagerx/core/graph.py
- eagerx/core/nodes.py
- examples/example_openai.py
> fix: render freeze

- README.rst
- docs/guide/getting_started/index.rst
- docs/guide/tutorials/colabs.rst
- eagerx/core/graph.py
- eagerx/core/nodes.py
> fix: extra render window opening, window bug, add tutorials 5,6,7 to docs

- docs/_shared/engine_node.rst
- docs/_shared/graph.rst
- docs/_shared/pendulum_agnostic.rst
- docs/guide/api_reference/env/index.rst
- docs/guide/tutorials/colabs.rst
- docs/guide/tutorials/pendulum/learn.rst
- eagerx/__init__.py
- eagerx/core/entities.py
- eagerx/core/env.py
- eagerx/core/specs.py
> fix: refactor `EagerxEnv` to `BaseEnv` that uses inheritance instead of composition.

- docs/_static/conda/ros_env.yml
> doc: update conda env

- README.rst
- docs/guide/tutorials/colabs.rst
- eagerx/core/env.py
- eagerx/core/graph.py
- eagerx/core/info.py
- eagerx/core/nodes.py
> fix: load entities before registering graph, colab rgb rendering, info bug

- docs/index.rst
Link to eagerx github was broken in landing page and this has now been fixed.
> docs: fix broken link

- eagerx/core/graph.py
- eagerx/core/graph_engine.py
> fix: deepcopy engine, list `EngineNodes` without outputs as dependency

- .github/workflows/ci.yml
> ci: fix poetry version and install gym separately

- .readthedocs.yaml
- docs/requirements.txt
- poetry.lock
- pyproject.toml
> docs: add requirements.txt for doc building and limit setuptools version

- eagerx/backends/__init__.py
- eagerx/backends/ros1.py
- eagerx/backends/single_process.py
- eagerx/core/entities.py
- eagerx/core/env.py
- eagerx/core/executable_engine.py
- eagerx/core/executable_node.py
- eagerx/core/graph.py
- eagerx/core/graph_engine.py
- eagerx/core/pubsub.py
- eagerx/core/register.py
- eagerx/core/rx_operators.py
- eagerx/core/rx_pipelines.py
- eagerx/core/supervisor.py
- eagerx/utils/utils.py
- examples/demo_async.py
- tests/test/nodes.py
- tests/test_integration_openai.py
> fix: synchronization with delays and cyclical connections

- eagerx/core/rx_operators.py
- eagerx/core/rx_pipelines.py
- eagerx/engines/openai_gym/engine.py
- eagerx/engines/openai_gym/enginenodes.py
- tests/test_integration_test.py
> fix: throttle bug

- .github/workflows/ci.yml
> ci: fix semantic release version

- README.md
> docs: Update README.md [ci skip]

- eagerx/core/entities.py
- eagerx/core/nodes.py
> fix: skipped observation bug, deprecated np.bool

- docs/index.rst
> docs: update videos

- README.md
- docs/index.rst
> docs: add drone landing gif
